// Placeholder sample data, bundled so the portal works immediately when opened.
// Replaced automatically once scripts/sync_sheet.py runs against your Google Sheet.
window.AMBASSADORS_FALLBACK = {
  "_meta": {
    "syncedAt": null,
    "source": "Sample data (bundled placeholder — not yet synced)",
    "count": 82,
    "includesContactInfo": true
  },
  "ambassadors": [
    {
      "srNo": 1,
      "name": "Vivaan Shah",
      "brandName": "Vivaan's Foodie Hub",
      "billingName": "Vivaan Shah Media",
      "code": "O2C-MA242",
      "city": "Mumbai",
      "state": "Maharashtra",
      "phone": "+91 9413223434",
      "email": "vivaan.shah@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "vivaanfoodiehub",
      "facebook": "",
      "whatsapp": "+91 9413223434",
      "kitchenType": "Bakery",
      "operationalSince": "2019",
      "servicesOffered": "Dine-in, Meal Subscriptions",
      "coverageAreas": "Mumbai",
      "specialties": "North Indian, South Indian, Thalis",
      "happyCustomers": "250+",
      "dishesServed": "50+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/vivaanfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 2,
      "name": "Aarav Reddy",
      "brandName": "Aarav's Cook Corner",
      "billingName": "Aarav Reddy Creations",
      "code": "O2C-MA384",
      "city": "Pune",
      "state": "Maharashtra",
      "phone": "+91 7509438221",
      "email": "aarav.reddy@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "aaravfoodiehub",
      "facebook": "",
      "whatsapp": "+91 7509438221",
      "kitchenType": "Catering Studio",
      "operationalSince": "2022",
      "servicesOffered": "Dine-in, Home Delivery",
      "coverageAreas": "Pune",
      "specialties": "Desserts, Tiffin Service, Bengali",
      "happyCustomers": "75+",
      "dishesServed": "100+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/aaravfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 3,
      "name": "Kiara Kulkarni",
      "brandName": "Kiara's Spice Table",
      "billingName": "Kiara Kulkarni Media",
      "code": "O2C-MA821",
      "city": "Pune",
      "state": "Maharashtra",
      "phone": "+91 7227916006",
      "email": "kiara.kulkarni@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "kiarakitchen",
      "facebook": "",
      "whatsapp": "+91 7227916006",
      "kitchenType": "Café",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Home Delivery, Workshops",
      "coverageAreas": "Pune",
      "specialties": "Street Food, Continental, Desserts, Biryani",
      "happyCustomers": "75+",
      "dishesServed": "150+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/kiarakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 4,
      "name": "Kavya Patel",
      "brandName": "Kavya's Home Chef",
      "billingName": "Kavya Patel",
      "code": "O2C-MA488",
      "city": "Pune",
      "state": "Maharashtra",
      "phone": "+91 7884593886",
      "email": "kavya.patel@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "kavyafoodiehub",
      "facebook": "",
      "whatsapp": "+91 7884593886",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Catering, Workshops",
      "coverageAreas": "Pune and nearby areas",
      "specialties": "Thalis, North Indian, Desserts",
      "happyCustomers": "200+",
      "dishesServed": "50+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/kavyafoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 5,
      "name": "Farhan Nair",
      "brandName": "Farhan's Kitchen Diaries",
      "billingName": "Farhan Nair Media",
      "code": "O2C-MA352",
      "city": "Nagpur",
      "state": "Maharashtra",
      "phone": "+91 9441183579",
      "email": "farhan.nair@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "farhanfoodiehub",
      "facebook": "",
      "whatsapp": "+91 9441183579",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Dine-in, Meal Subscriptions, Workshops",
      "coverageAreas": "Nagpur and nearby areas",
      "specialties": "Desserts, Thalis, Biryani, Gujarati",
      "happyCustomers": "100+",
      "dishesServed": "200+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/farhanfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 6,
      "name": "Arjun Chatterjee",
      "brandName": "Arjun's Cook Corner",
      "billingName": "Arjun Chatterjee",
      "code": "O2C-MA641",
      "city": "Nagpur",
      "state": "Maharashtra",
      "phone": "+91 7823882512",
      "email": "arjun.chatterjee@example.com",
      "profile": "Passionate about food, flavour and community. Runs a popular kitchen known for consistent quality and a love for innovation.",
      "instagram": "arjuncooks",
      "facebook": "",
      "whatsapp": "+91 7823882512",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2023",
      "servicesOffered": "Meal Subscriptions, Workshops",
      "coverageAreas": "Nagpur and nearby areas",
      "specialties": "Catering, Desserts, South Indian, Street Food",
      "happyCustomers": "150+",
      "dishesServed": "150+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/arjuncooks",
      "photoUrl": ""
    },
    {
      "srNo": 7,
      "name": "Neha Iyer",
      "brandName": "Neha's Kitchen Diaries",
      "billingName": "Neha Iyer Media",
      "code": "O2C-MA256",
      "city": "Nagpur",
      "state": "Maharashtra",
      "phone": "+91 8225231174",
      "email": "neha.iyer@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "nehakitchen",
      "facebook": "",
      "whatsapp": "+91 8225231174",
      "kitchenType": "Bakery",
      "operationalSince": "2018",
      "servicesOffered": "Catering, Meal Subscriptions",
      "coverageAreas": "Nagpur",
      "specialties": "North Indian, South Indian, Desserts, Street Food",
      "happyCustomers": "75+",
      "dishesServed": "200+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/nehakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 8,
      "name": "Arjun Joshi",
      "brandName": "Arjun's Home Chef",
      "billingName": "Arjun Joshi Media",
      "code": "O2C-MA775",
      "city": "Nagpur",
      "state": "Maharashtra",
      "phone": "+91 8557482063",
      "email": "arjun.joshi@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "arjuneats",
      "facebook": "",
      "whatsapp": "+91 8557482063",
      "kitchenType": "Catering Studio",
      "operationalSince": "2022",
      "servicesOffered": "Dine-in, Meal Subscriptions, Workshops",
      "coverageAreas": "Nagpur",
      "specialties": "Gujarati, Thalis, Street Food",
      "happyCustomers": "300+",
      "dishesServed": "30+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/arjuneats",
      "photoUrl": ""
    },
    {
      "srNo": 9,
      "name": "Karan Sharma",
      "brandName": "Karan's Chef's Table",
      "billingName": "Karan Sharma Media",
      "code": "O2C-DE702",
      "city": "Delhi",
      "state": "Delhi",
      "phone": "+91 7721610942",
      "email": "karan.sharma@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "karancooks",
      "facebook": "",
      "whatsapp": "+91 7721610942",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Bulk Orders, Home Delivery",
      "coverageAreas": "Delhi",
      "specialties": "Desserts, South Indian, Gujarati",
      "happyCustomers": "100+",
      "dishesServed": "200+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/karancooks",
      "photoUrl": ""
    },
    {
      "srNo": 10,
      "name": "Anika Menon",
      "brandName": "Anika's Cook Corner",
      "billingName": "Anika Menon Media",
      "code": "O2C-KA196",
      "city": "Bengaluru",
      "state": "Karnataka",
      "phone": "+91 7317696374",
      "email": "anika.menon@example.com",
      "profile": "Restaurant consultant and on-air cooking demo host with a decade in commercial kitchens.",
      "instagram": "anikaeats",
      "facebook": "",
      "whatsapp": "+91 7317696374",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Dine-in, Meal Subscriptions, Workshops",
      "coverageAreas": "Bengaluru",
      "specialties": "Catering, Tiffin Service, South Indian",
      "happyCustomers": "125+",
      "dishesServed": "50+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/anikaeats",
      "photoUrl": ""
    },
    {
      "srNo": 11,
      "name": "Ishaan Banerjee",
      "brandName": "Ishaan's Home Chef",
      "billingName": "Ishaan Banerjee Creations",
      "code": "O2C-KA573",
      "city": "Bengaluru",
      "state": "Karnataka",
      "phone": "+91 7818519880",
      "email": "ishaan.banerjee@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "ishaancooks",
      "facebook": "",
      "whatsapp": "+91 7818519880",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Home Delivery, Meal Subscriptions",
      "coverageAreas": "Bengaluru and nearby areas",
      "specialties": "South Indian, Thalis, Biryani",
      "happyCustomers": "250+",
      "dishesServed": "30+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/ishaancooks",
      "photoUrl": ""
    },
    {
      "srNo": 12,
      "name": "Aarav Chatterjee",
      "brandName": "Aarav's Kitchen Diaries",
      "billingName": "Aarav Chatterjee",
      "code": "O2C-KA392",
      "city": "Bengaluru",
      "state": "Karnataka",
      "phone": "+91 8386182845",
      "email": "aarav.chatterjee@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "aaraveats",
      "facebook": "",
      "whatsapp": "+91 8386182845",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2018",
      "servicesOffered": "Bulk Orders, Catering",
      "coverageAreas": "Bengaluru",
      "specialties": "North Indian, Bengali, Gujarati",
      "happyCustomers": "300+",
      "dishesServed": "150+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/aaraveats",
      "photoUrl": ""
    },
    {
      "srNo": 13,
      "name": "Pooja Reddy",
      "brandName": "Pooja's Kitchen Studio",
      "billingName": "Pooja Reddy Enterprises",
      "code": "O2C-KA971",
      "city": "Bengaluru",
      "state": "Karnataka",
      "phone": "+91 7608918981",
      "email": "pooja.reddy@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "poojacooks",
      "facebook": "",
      "whatsapp": "+91 7608918981",
      "kitchenType": "Bakery",
      "operationalSince": "2022",
      "servicesOffered": "Bulk Orders, Workshops",
      "coverageAreas": "Bengaluru and nearby areas",
      "specialties": "South Indian, Bengali, Thalis, North Indian",
      "happyCustomers": "200+",
      "dishesServed": "75+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/poojacooks",
      "photoUrl": ""
    },
    {
      "srNo": 14,
      "name": "Anika Shah",
      "brandName": "Anika's Cook Corner",
      "billingName": "Anika Shah Media",
      "code": "O2C-KA787",
      "city": "Mysuru",
      "state": "Karnataka",
      "phone": "+91 9115149321",
      "email": "anika.shah@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "anikakitchen",
      "facebook": "",
      "whatsapp": "+91 9115149321",
      "kitchenType": "Café",
      "operationalSince": "2018",
      "servicesOffered": "Dine-in, Home Delivery, Workshops",
      "coverageAreas": "Mysuru and nearby areas",
      "specialties": "South Indian, Gujarati, Thalis",
      "happyCustomers": "125+",
      "dishesServed": "75+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/anikakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 15,
      "name": "Dev Joshi",
      "brandName": "Dev's Kitchen Diaries",
      "billingName": "Dev Joshi Enterprises",
      "code": "O2C-KA783",
      "city": "Mysuru",
      "state": "Karnataka",
      "phone": "+91 9677482692",
      "email": "dev.joshi@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "devkitchen",
      "facebook": "",
      "whatsapp": "+91 9677482692",
      "kitchenType": "Café",
      "operationalSince": "2019",
      "servicesOffered": "Bulk Orders, Catering",
      "coverageAreas": "Mysuru",
      "specialties": "South Indian, Gujarati, Biryani",
      "happyCustomers": "150+",
      "dishesServed": "150+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/devkitchen",
      "photoUrl": ""
    },
    {
      "srNo": 16,
      "name": "Vihaan Gupta",
      "brandName": "Vihaan's Cook Corner",
      "billingName": "Vihaan Gupta Creations",
      "code": "O2C-KA145",
      "city": "Mysuru",
      "state": "Karnataka",
      "phone": "+91 7011653719",
      "email": "vihaan.gupta@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "vihaaneats",
      "facebook": "",
      "whatsapp": "+91 7011653719",
      "kitchenType": "Bakery",
      "operationalSince": "2022",
      "servicesOffered": "Bulk Orders, Dine-in, Meal Subscriptions",
      "coverageAreas": "Mysuru and nearby areas",
      "specialties": "South Indian, Tiffin Service, Biryani",
      "happyCustomers": "100+",
      "dishesServed": "100+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/vihaaneats",
      "photoUrl": ""
    },
    {
      "srNo": 17,
      "name": "Rahul Verma",
      "brandName": "Rahul's Spice Table",
      "billingName": "Rahul Verma Media",
      "code": "O2C-TA798",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "phone": "+91 7817697416",
      "email": "rahul.verma@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "rahuleats",
      "facebook": "",
      "whatsapp": "+91 7817697416",
      "kitchenType": "Catering Studio",
      "operationalSince": "2024",
      "servicesOffered": "Bulk Orders, Dine-in, Meal Subscriptions",
      "coverageAreas": "Chennai",
      "specialties": "Biryani, Tiffin Service, Bakery",
      "happyCustomers": "125+",
      "dishesServed": "75+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/rahuleats",
      "photoUrl": ""
    },
    {
      "srNo": 18,
      "name": "Reyansh Chatterjee",
      "brandName": "Reyansh's Kitchen Studio",
      "billingName": "Reyansh Chatterjee",
      "code": "O2C-TA327",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "phone": "+91 7653970332",
      "email": "reyansh.chatterjee@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "reyansheats",
      "facebook": "",
      "whatsapp": "+91 7653970332",
      "kitchenType": "Café",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Home Delivery, Workshops",
      "coverageAreas": "Chennai and nearby areas",
      "specialties": "Bakery, Desserts, Street Food",
      "happyCustomers": "250+",
      "dishesServed": "200+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/reyansheats",
      "photoUrl": ""
    },
    {
      "srNo": 19,
      "name": "Kavya Kapoor",
      "brandName": "Kavya's Kitchen Studio",
      "billingName": "Kavya Kapoor Enterprises",
      "code": "O2C-TA998",
      "city": "Chennai",
      "state": "Tamil Nadu",
      "phone": "+91 7855933405",
      "email": "kavya.kapoor@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "kavyakitchen",
      "facebook": "",
      "whatsapp": "+91 7855933405",
      "kitchenType": "Café",
      "operationalSince": "2018",
      "servicesOffered": "Dine-in, Home Delivery, Workshops",
      "coverageAreas": "Chennai",
      "specialties": "Tiffin Service, Desserts, Bakery, Gujarati",
      "happyCustomers": "250+",
      "dishesServed": "30+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/kavyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 20,
      "name": "Rahul Banerjee",
      "brandName": "Rahul's Culinary Co.",
      "billingName": "Rahul Banerjee Creations",
      "code": "O2C-TA738",
      "city": "Coimbatore",
      "state": "Tamil Nadu",
      "phone": "+91 8028696951",
      "email": "rahul.banerjee@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "rahulcooks",
      "facebook": "",
      "whatsapp": "+91 8028696951",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Catering, Dine-in, Meal Subscriptions",
      "coverageAreas": "Coimbatore",
      "specialties": "Bakery, Street Food, Gujarati, Biryani",
      "happyCustomers": "150+",
      "dishesServed": "100+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/rahulcooks",
      "photoUrl": ""
    },
    {
      "srNo": 21,
      "name": "Aarav Mehta",
      "brandName": "Aarav's Kitchen Diaries",
      "billingName": "Aarav Mehta Media",
      "code": "O2C-TA540",
      "city": "Coimbatore",
      "state": "Tamil Nadu",
      "phone": "+91 9574786019",
      "email": "aarav.mehta@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "aaraveats",
      "facebook": "",
      "whatsapp": "+91 9574786019",
      "kitchenType": "Bakery",
      "operationalSince": "2023",
      "servicesOffered": "Dine-in, Meal Subscriptions, Workshops",
      "coverageAreas": "Coimbatore and nearby areas",
      "specialties": "Gujarati, Continental, Biryani",
      "happyCustomers": "200+",
      "dishesServed": "30+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/aaraveats",
      "photoUrl": ""
    },
    {
      "srNo": 22,
      "name": "Navya Patel",
      "brandName": "Navya's Foodie Hub",
      "billingName": "Navya Patel Media",
      "code": "O2C-TE125",
      "city": "Hyderabad",
      "state": "Telangana",
      "phone": "+91 7151442092",
      "email": "navya.patel@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "navyakitchen",
      "facebook": "",
      "whatsapp": "+91 7151442092",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Dine-in, Workshops",
      "coverageAreas": "Hyderabad",
      "specialties": "Tiffin Service, Bakery, Continental",
      "happyCustomers": "75+",
      "dishesServed": "100+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/navyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 23,
      "name": "Pooja Das",
      "brandName": "Pooja's Kitchen Studio",
      "billingName": "Pooja Das Media",
      "code": "O2C-TE968",
      "city": "Hyderabad",
      "state": "Telangana",
      "phone": "+91 7397669829",
      "email": "pooja.das@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "poojakitchen",
      "facebook": "",
      "whatsapp": "+91 7397669829",
      "kitchenType": "Catering Studio",
      "operationalSince": "2021",
      "servicesOffered": "Catering, Meal Subscriptions, Workshops",
      "coverageAreas": "Hyderabad and nearby areas",
      "specialties": "Bengali, Gujarati, Bakery, Catering",
      "happyCustomers": "150+",
      "dishesServed": "50+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/poojakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 24,
      "name": "Pooja Menon",
      "brandName": "Pooja's Foodie Hub",
      "billingName": "Pooja Menon Creations",
      "code": "O2C-GU550",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "phone": "+91 7253847450",
      "email": "pooja.menon@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "poojakitchen",
      "facebook": "",
      "whatsapp": "+91 7253847450",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2021",
      "servicesOffered": "Catering, Home Delivery, Workshops",
      "coverageAreas": "Ahmedabad and nearby areas",
      "specialties": "Biryani, Thalis, Bakery",
      "happyCustomers": "250+",
      "dishesServed": "75+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/poojakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 25,
      "name": "Aman Verma",
      "brandName": "Aman's Foodie Hub",
      "billingName": "Aman Verma",
      "code": "O2C-GU498",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "phone": "+91 9964986556",
      "email": "aman.verma@example.com",
      "profile": "Passionate about food, flavour and community. Runs a popular kitchen known for consistent quality and a love for innovation.",
      "instagram": "amankitchen",
      "facebook": "",
      "whatsapp": "+91 9964986556",
      "kitchenType": "Catering Studio",
      "operationalSince": "2019",
      "servicesOffered": "Catering, Dine-in, Home Delivery",
      "coverageAreas": "Ahmedabad and nearby areas",
      "specialties": "Bakery, Tiffin Service, Gujarati, Bengali",
      "happyCustomers": "150+",
      "dishesServed": "100+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/amankitchen",
      "photoUrl": ""
    },
    {
      "srNo": 26,
      "name": "Varun Kapoor",
      "brandName": "Varun's Cook Corner",
      "billingName": "Varun Kapoor Media",
      "code": "O2C-GU960",
      "city": "Ahmedabad",
      "state": "Gujarat",
      "phone": "+91 8531526728",
      "email": "varun.kapoor@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "varuncooks",
      "facebook": "",
      "whatsapp": "+91 8531526728",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2018",
      "servicesOffered": "Dine-in, Meal Subscriptions",
      "coverageAreas": "Ahmedabad",
      "specialties": "South Indian, Catering, Bakery",
      "happyCustomers": "150+",
      "dishesServed": "100+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/varuncooks",
      "photoUrl": ""
    },
    {
      "srNo": 27,
      "name": "Rohan Kapoor",
      "brandName": "Rohan's Cook Corner",
      "billingName": "Rohan Kapoor Creations",
      "code": "O2C-GU870",
      "city": "Surat",
      "state": "Gujarat",
      "phone": "+91 9726065255",
      "email": "rohan.kapoor@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "rohanfoodiehub",
      "facebook": "",
      "whatsapp": "+91 9726065255",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Dine-in, Home Delivery",
      "coverageAreas": "Surat and nearby areas",
      "specialties": "Desserts, Thalis, South Indian",
      "happyCustomers": "125+",
      "dishesServed": "30+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/rohanfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 28,
      "name": "Anika Nair",
      "brandName": "Anika's Flavour Lab",
      "billingName": "Anika Nair Enterprises",
      "code": "O2C-GU677",
      "city": "Surat",
      "state": "Gujarat",
      "phone": "+91 7714270952",
      "email": "anika.nair@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "anikaeats",
      "facebook": "",
      "whatsapp": "+91 7714270952",
      "kitchenType": "Bakery",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Home Delivery, Meal Subscriptions",
      "coverageAreas": "Surat",
      "specialties": "Street Food, South Indian, Bengali",
      "happyCustomers": "250+",
      "dishesServed": "100+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/anikaeats",
      "photoUrl": ""
    },
    {
      "srNo": 29,
      "name": "Aadhya Gupta",
      "brandName": "Aadhya's Chef's Table",
      "billingName": "Aadhya Gupta Media",
      "code": "O2C-GU204",
      "city": "Surat",
      "state": "Gujarat",
      "phone": "+91 9284549529",
      "email": "aadhya.gupta@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "aadhyaeats",
      "facebook": "",
      "whatsapp": "+91 9284549529",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Home Delivery, Meal Subscriptions",
      "coverageAreas": "Surat and nearby areas",
      "specialties": "Gujarati, Bakery, Desserts, South Indian",
      "happyCustomers": "250+",
      "dishesServed": "100+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/aadhyaeats",
      "photoUrl": ""
    },
    {
      "srNo": 30,
      "name": "Rahul Das",
      "brandName": "Rahul's Home Chef",
      "billingName": "Rahul Das",
      "code": "O2C-GU280",
      "city": "Surat",
      "state": "Gujarat",
      "phone": "+91 9404578386",
      "email": "rahul.das@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "rahulcooks",
      "facebook": "",
      "whatsapp": "+91 9404578386",
      "kitchenType": "Bakery",
      "operationalSince": "2022",
      "servicesOffered": "Catering, Dine-in, Workshops",
      "coverageAreas": "Surat",
      "specialties": "Thalis, South Indian, Street Food, Continental",
      "happyCustomers": "250+",
      "dishesServed": "75+",
      "rating": 4.3,
      "profileUrl": "https://instagram.com/rahulcooks",
      "photoUrl": ""
    },
    {
      "srNo": 31,
      "name": "Diya Menon",
      "brandName": "Diya's Foodie Hub",
      "billingName": "Diya Menon Creations",
      "code": "O2C-GU916",
      "city": "Vadodara",
      "state": "Gujarat",
      "phone": "+91 7846554608",
      "email": "diya.menon@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "diyakitchen",
      "facebook": "",
      "whatsapp": "+91 7846554608",
      "kitchenType": "Catering Studio",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Home Delivery, Meal Subscriptions",
      "coverageAreas": "Vadodara and nearby areas",
      "specialties": "Thalis, Bakery, Continental",
      "happyCustomers": "300+",
      "dishesServed": "100+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/diyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 32,
      "name": "Sai Mehta",
      "brandName": "Sai's Foodie Hub",
      "billingName": "Sai Mehta",
      "code": "O2C-GU808",
      "city": "Vadodara",
      "state": "Gujarat",
      "phone": "+91 7797250135",
      "email": "sai.mehta@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "saieats",
      "facebook": "",
      "whatsapp": "+91 7797250135",
      "kitchenType": "Café",
      "operationalSince": "2020",
      "servicesOffered": "Catering, Dine-in, Meal Subscriptions",
      "coverageAreas": "Vadodara and nearby areas",
      "specialties": "Tiffin Service, Gujarati, Desserts, Bengali",
      "happyCustomers": "125+",
      "dishesServed": "30+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/saieats",
      "photoUrl": ""
    },
    {
      "srNo": 33,
      "name": "Rohan Iyer",
      "brandName": "Rohan's Kitchen Tales",
      "billingName": "Rohan Iyer Media",
      "code": "O2C-GU296",
      "city": "Vadodara",
      "state": "Gujarat",
      "phone": "+91 7709073464",
      "email": "rohan.iyer@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "rohankitchen",
      "facebook": "",
      "whatsapp": "+91 7709073464",
      "kitchenType": "Café",
      "operationalSince": "2018",
      "servicesOffered": "Bulk Orders, Catering, Home Delivery",
      "coverageAreas": "Vadodara",
      "specialties": "Desserts, Biryani, Street Food",
      "happyCustomers": "50+",
      "dishesServed": "150+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/rohankitchen",
      "photoUrl": ""
    },
    {
      "srNo": 34,
      "name": "Sneha Iyer",
      "brandName": "Sneha's Kitchen Studio",
      "billingName": "Sneha Iyer Creations",
      "code": "O2C-RA580",
      "city": "Jaipur",
      "state": "Rajasthan",
      "phone": "+91 8568667733",
      "email": "sneha.iyer@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "snehafoodiehub",
      "facebook": "",
      "whatsapp": "+91 8568667733",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Catering, Home Delivery",
      "coverageAreas": "Jaipur",
      "specialties": "South Indian, Tiffin Service, Bakery, Continental",
      "happyCustomers": "150+",
      "dishesServed": "30+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/snehafoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 35,
      "name": "Krishna Joshi",
      "brandName": "Krishna's Cook Corner",
      "billingName": "Krishna Joshi Media",
      "code": "O2C-RA894",
      "city": "Jaipur",
      "state": "Rajasthan",
      "phone": "+91 8712359856",
      "email": "krishna.joshi@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "krishnakitchen",
      "facebook": "",
      "whatsapp": "+91 8712359856",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2020",
      "servicesOffered": "Catering, Dine-in, Meal Subscriptions",
      "coverageAreas": "Jaipur and nearby areas",
      "specialties": "Bengali, Tiffin Service, North Indian, South Indian",
      "happyCustomers": "75+",
      "dishesServed": "50+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/krishnakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 36,
      "name": "Ananya Sharma",
      "brandName": "Ananya's Cook Corner",
      "billingName": "Ananya Sharma",
      "code": "O2C-RA805",
      "city": "Udaipur",
      "state": "Rajasthan",
      "phone": "+91 8945871592",
      "email": "ananya.sharma@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "ananyakitchen",
      "facebook": "",
      "whatsapp": "+91 8945871592",
      "kitchenType": "Catering Studio",
      "operationalSince": "2018",
      "servicesOffered": "Bulk Orders, Catering",
      "coverageAreas": "Udaipur and nearby areas",
      "specialties": "Tiffin Service, Continental, South Indian, Thalis",
      "happyCustomers": "125+",
      "dishesServed": "200+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/ananyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 37,
      "name": "Kabir Gupta",
      "brandName": "Kabir's Kitchen Studio",
      "billingName": "Kabir Gupta Media",
      "code": "O2C-UT911",
      "city": "Lucknow",
      "state": "Uttar Pradesh",
      "phone": "+91 8007987993",
      "email": "kabir.gupta@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "kabircooks",
      "facebook": "",
      "whatsapp": "+91 8007987993",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Dine-in, Home Delivery, Workshops",
      "coverageAreas": "Lucknow and nearby areas",
      "specialties": "Tiffin Service, Bakery, Street Food, Gujarati",
      "happyCustomers": "50+",
      "dishesServed": "100+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/kabircooks",
      "photoUrl": ""
    },
    {
      "srNo": 38,
      "name": "Isha Shah",
      "brandName": "Isha's Kitchen Studio",
      "billingName": "Isha Shah Enterprises",
      "code": "O2C-UT334",
      "city": "Lucknow",
      "state": "Uttar Pradesh",
      "phone": "+91 9209585392",
      "email": "isha.shah@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "ishaeats",
      "facebook": "",
      "whatsapp": "+91 9209585392",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Catering, Workshops",
      "coverageAreas": "Lucknow and nearby areas",
      "specialties": "Biryani, Continental, Gujarati",
      "happyCustomers": "250+",
      "dishesServed": "200+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/ishaeats",
      "photoUrl": ""
    },
    {
      "srNo": 39,
      "name": "Sai Menon",
      "brandName": "Sai's Spice Table",
      "billingName": "Sai Menon",
      "code": "O2C-UT441",
      "city": "Lucknow",
      "state": "Uttar Pradesh",
      "phone": "+91 8052097835",
      "email": "sai.menon@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "saifoodiehub",
      "facebook": "",
      "whatsapp": "+91 8052097835",
      "kitchenType": "Café",
      "operationalSince": "2020",
      "servicesOffered": "Catering, Dine-in",
      "coverageAreas": "Lucknow",
      "specialties": "Street Food, Catering, Bakery, Gujarati",
      "happyCustomers": "200+",
      "dishesServed": "30+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/saifoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 40,
      "name": "Neha Sharma",
      "brandName": "Neha's Kitchen Tales",
      "billingName": "Neha Sharma",
      "code": "O2C-UT523",
      "city": "Noida",
      "state": "Uttar Pradesh",
      "phone": "+91 7177634586",
      "email": "neha.sharma@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "nehaeats",
      "facebook": "",
      "whatsapp": "+91 7177634586",
      "kitchenType": "Catering Studio",
      "operationalSince": "2023",
      "servicesOffered": "Dine-in, Meal Subscriptions, Workshops",
      "coverageAreas": "Noida",
      "specialties": "Thalis, Street Food, Gujarati",
      "happyCustomers": "300+",
      "dishesServed": "30+",
      "rating": 4.3,
      "profileUrl": "https://instagram.com/nehaeats",
      "photoUrl": ""
    },
    {
      "srNo": 41,
      "name": "Isha Patel",
      "brandName": "Isha's Home Chef",
      "billingName": "Isha Patel Creations",
      "code": "O2C-UT664",
      "city": "Noida",
      "state": "Uttar Pradesh",
      "phone": "+91 7044882384",
      "email": "isha.patel@example.com",
      "profile": "Restaurant consultant and on-air cooking demo host with a decade in commercial kitchens.",
      "instagram": "ishaeats",
      "facebook": "",
      "whatsapp": "+91 7044882384",
      "kitchenType": "Bakery",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Home Delivery",
      "coverageAreas": "Noida and nearby areas",
      "specialties": "South Indian, Catering, Biryani, Continental",
      "happyCustomers": "150+",
      "dishesServed": "100+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/ishaeats",
      "photoUrl": ""
    },
    {
      "srNo": 42,
      "name": "Priya Patel",
      "brandName": "Priya's Flavour Lab",
      "billingName": "Priya Patel Media",
      "code": "O2C-UT492",
      "city": "Noida",
      "state": "Uttar Pradesh",
      "phone": "+91 7624588561",
      "email": "priya.patel@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "priyaeats",
      "facebook": "",
      "whatsapp": "+91 7624588561",
      "kitchenType": "Bakery",
      "operationalSince": "2022",
      "servicesOffered": "Catering, Home Delivery",
      "coverageAreas": "Noida",
      "specialties": "Desserts, Gujarati, Street Food, North Indian",
      "happyCustomers": "300+",
      "dishesServed": "50+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/priyaeats",
      "photoUrl": ""
    },
    {
      "srNo": 43,
      "name": "Priya Malhotra",
      "brandName": "Priya's Spice Table",
      "billingName": "Priya Malhotra",
      "code": "O2C-UT566",
      "city": "Noida",
      "state": "Uttar Pradesh",
      "phone": "+91 8054434727",
      "email": "priya.malhotra@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "priyakitchen",
      "facebook": "",
      "whatsapp": "+91 8054434727",
      "kitchenType": "Catering Studio",
      "operationalSince": "2018",
      "servicesOffered": "Bulk Orders, Dine-in, Home Delivery",
      "coverageAreas": "Noida and nearby areas",
      "specialties": "Tiffin Service, Continental, Bakery, Bengali",
      "happyCustomers": "100+",
      "dishesServed": "150+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/priyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 44,
      "name": "Reyansh Das",
      "brandName": "Reyansh's Culinary Co.",
      "billingName": "Reyansh Das",
      "code": "O2C-UT115",
      "city": "Kanpur",
      "state": "Uttar Pradesh",
      "phone": "+91 9367328894",
      "email": "reyansh.das@example.com",
      "profile": "Restaurant consultant and on-air cooking demo host with a decade in commercial kitchens.",
      "instagram": "reyanshcooks",
      "facebook": "",
      "whatsapp": "+91 9367328894",
      "kitchenType": "Café",
      "operationalSince": "2023",
      "servicesOffered": "Dine-in, Home Delivery",
      "coverageAreas": "Kanpur and nearby areas",
      "specialties": "Desserts, Bengali, Bakery, South Indian",
      "happyCustomers": "300+",
      "dishesServed": "150+",
      "rating": 4.3,
      "profileUrl": "https://instagram.com/reyanshcooks",
      "photoUrl": ""
    },
    {
      "srNo": 45,
      "name": "Arjun Patel",
      "brandName": "Arjun's Kitchen Diaries",
      "billingName": "Arjun Patel Media",
      "code": "O2C-UT864",
      "city": "Kanpur",
      "state": "Uttar Pradesh",
      "phone": "+91 7296166881",
      "email": "arjun.patel@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "arjuneats",
      "facebook": "",
      "whatsapp": "+91 7296166881",
      "kitchenType": "Catering Studio",
      "operationalSince": "2019",
      "servicesOffered": "Bulk Orders, Dine-in",
      "coverageAreas": "Kanpur",
      "specialties": "North Indian, Tiffin Service, Desserts, Catering",
      "happyCustomers": "125+",
      "dishesServed": "150+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/arjuneats",
      "photoUrl": ""
    },
    {
      "srNo": 46,
      "name": "Diya Reddy",
      "brandName": "Diya's Home Chef",
      "billingName": "Diya Reddy Enterprises",
      "code": "O2C-UT724",
      "city": "Kanpur",
      "state": "Uttar Pradesh",
      "phone": "+91 9853560140",
      "email": "diya.reddy@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "diyafoodiehub",
      "facebook": "",
      "whatsapp": "+91 9853560140",
      "kitchenType": "Catering Studio",
      "operationalSince": "2020",
      "servicesOffered": "Dine-in, Meal Subscriptions",
      "coverageAreas": "Kanpur and nearby areas",
      "specialties": "Thalis, Continental, Street Food",
      "happyCustomers": "100+",
      "dishesServed": "30+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/diyafoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 47,
      "name": "Divya Mehta",
      "brandName": "Divya's Cook Corner",
      "billingName": "Divya Mehta Creations",
      "code": "O2C-WE567",
      "city": "Kolkata",
      "state": "West Bengal",
      "phone": "+91 9769849599",
      "email": "divya.mehta@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "divyaeats",
      "facebook": "",
      "whatsapp": "+91 9769849599",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Bulk Orders, Dine-in, Home Delivery",
      "coverageAreas": "Kolkata and nearby areas",
      "specialties": "Bengali, Desserts, Tiffin Service, Street Food",
      "happyCustomers": "250+",
      "dishesServed": "75+",
      "rating": 4.3,
      "profileUrl": "https://instagram.com/divyaeats",
      "photoUrl": ""
    },
    {
      "srNo": 48,
      "name": "Vihaan Kulkarni",
      "brandName": "Vihaan's Flavour Lab",
      "billingName": "Vihaan Kulkarni Creations",
      "code": "O2C-WE894",
      "city": "Kolkata",
      "state": "West Bengal",
      "phone": "+91 9617740162",
      "email": "vihaan.kulkarni@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "vihaancooks",
      "facebook": "",
      "whatsapp": "+91 9617740162",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Bulk Orders, Catering, Workshops",
      "coverageAreas": "Kolkata",
      "specialties": "Catering, South Indian, North Indian",
      "happyCustomers": "200+",
      "dishesServed": "200+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/vihaancooks",
      "photoUrl": ""
    },
    {
      "srNo": 49,
      "name": "Kiara Kapoor",
      "brandName": "Kiara's Cook Corner",
      "billingName": "Kiara Kapoor Media",
      "code": "O2C-WE305",
      "city": "Kolkata",
      "state": "West Bengal",
      "phone": "+91 7433080701",
      "email": "kiara.kapoor@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "kiarakitchen",
      "facebook": "",
      "whatsapp": "+91 7433080701",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Bulk Orders, Catering, Dine-in",
      "coverageAreas": "Kolkata and nearby areas",
      "specialties": "Tiffin Service, Desserts, South Indian, Continental",
      "happyCustomers": "250+",
      "dishesServed": "150+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/kiarakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 50,
      "name": "Aarav Shah",
      "brandName": "Aarav's Kitchen Tales",
      "billingName": "Aarav Shah Enterprises",
      "code": "O2C-CH565",
      "city": "Chandigarh",
      "state": "Chandigarh",
      "phone": "+91 8207798188",
      "email": "aarav.shah@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "aaraveats",
      "facebook": "",
      "whatsapp": "+91 8207798188",
      "kitchenType": "Bakery",
      "operationalSince": "2019",
      "servicesOffered": "Catering, Home Delivery, Workshops",
      "coverageAreas": "Chandigarh and nearby areas",
      "specialties": "Continental, North Indian, Bengali",
      "happyCustomers": "75+",
      "dishesServed": "200+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/aaraveats",
      "photoUrl": ""
    },
    {
      "srNo": 51,
      "name": "Navya Banerjee",
      "brandName": "Navya's Culinary Co.",
      "billingName": "Navya Banerjee Media",
      "code": "O2C-CH146",
      "city": "Chandigarh",
      "state": "Chandigarh",
      "phone": "+91 7121949893",
      "email": "navya.banerjee@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "navyacooks",
      "facebook": "",
      "whatsapp": "+91 7121949893",
      "kitchenType": "Bakery",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Home Delivery",
      "coverageAreas": "Chandigarh and nearby areas",
      "specialties": "Bakery, Continental, Desserts",
      "happyCustomers": "100+",
      "dishesServed": "100+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/navyacooks",
      "photoUrl": ""
    },
    {
      "srNo": 52,
      "name": "Sneha Kulkarni",
      "brandName": "Sneha's Cook Corner",
      "billingName": "Sneha Kulkarni Creations",
      "code": "O2C-CH133",
      "city": "Chandigarh",
      "state": "Chandigarh",
      "phone": "+91 9261958566",
      "email": "sneha.kulkarni@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "snehaeats",
      "facebook": "",
      "whatsapp": "+91 9261958566",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2021",
      "servicesOffered": "Bulk Orders, Catering, Dine-in",
      "coverageAreas": "Chandigarh and nearby areas",
      "specialties": "Catering, Desserts, Gujarati",
      "happyCustomers": "150+",
      "dishesServed": "50+",
      "rating": 5.0,
      "profileUrl": "https://instagram.com/snehaeats",
      "photoUrl": ""
    },
    {
      "srNo": 53,
      "name": "Farhan Gupta",
      "brandName": "Farhan's Foodie Hub",
      "billingName": "Farhan Gupta Enterprises",
      "code": "O2C-CH151",
      "city": "Chandigarh",
      "state": "Chandigarh",
      "phone": "+91 9578153713",
      "email": "farhan.gupta@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "farhankitchen",
      "facebook": "",
      "whatsapp": "+91 9578153713",
      "kitchenType": "Café",
      "operationalSince": "2024",
      "servicesOffered": "Bulk Orders, Meal Subscriptions",
      "coverageAreas": "Chandigarh",
      "specialties": "Gujarati, Thalis, Bengali",
      "happyCustomers": "100+",
      "dishesServed": "150+",
      "rating": 4.3,
      "profileUrl": "https://instagram.com/farhankitchen",
      "photoUrl": ""
    },
    {
      "srNo": 54,
      "name": "Ishaan Joshi",
      "brandName": "Ishaan's Kitchen Diaries",
      "billingName": "Ishaan Joshi Media",
      "code": "O2C-MA212",
      "city": "Bhopal",
      "state": "Madhya Pradesh",
      "phone": "+91 9166113379",
      "email": "ishaan.joshi@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "ishaancooks",
      "facebook": "",
      "whatsapp": "+91 9166113379",
      "kitchenType": "Bakery",
      "operationalSince": "2018",
      "servicesOffered": "Bulk Orders, Catering",
      "coverageAreas": "Bhopal",
      "specialties": "North Indian, Biryani, Street Food, Tiffin Service",
      "happyCustomers": "75+",
      "dishesServed": "100+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/ishaancooks",
      "photoUrl": ""
    },
    {
      "srNo": 55,
      "name": "Rahul Pillai",
      "brandName": "Rahul's Chef's Table",
      "billingName": "Rahul Pillai Enterprises",
      "code": "O2C-MA562",
      "city": "Bhopal",
      "state": "Madhya Pradesh",
      "phone": "+91 8650939038",
      "email": "rahul.pillai@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "rahulcooks",
      "facebook": "",
      "whatsapp": "+91 8650939038",
      "kitchenType": "Catering Studio",
      "operationalSince": "2023",
      "servicesOffered": "Meal Subscriptions, Workshops",
      "coverageAreas": "Bhopal and nearby areas",
      "specialties": "Continental, Catering, North Indian, Bengali",
      "happyCustomers": "75+",
      "dishesServed": "100+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/rahulcooks",
      "photoUrl": ""
    },
    {
      "srNo": 56,
      "name": "Arjun Gupta",
      "brandName": "Arjun's Spice Table",
      "billingName": "Arjun Gupta Media",
      "code": "O2C-MA167",
      "city": "Indore",
      "state": "Madhya Pradesh",
      "phone": "+91 7413546046",
      "email": "arjun.gupta@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "arjunfoodiehub",
      "facebook": "",
      "whatsapp": "+91 7413546046",
      "kitchenType": "Bakery",
      "operationalSince": "2023",
      "servicesOffered": "Catering, Dine-in, Meal Subscriptions",
      "coverageAreas": "Indore and nearby areas",
      "specialties": "Gujarati, Bengali, Bakery, South Indian",
      "happyCustomers": "125+",
      "dishesServed": "100+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/arjunfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 57,
      "name": "Sara Banerjee",
      "brandName": "Sara's Spice Table",
      "billingName": "Sara Banerjee",
      "code": "O2C-MA508",
      "city": "Indore",
      "state": "Madhya Pradesh",
      "phone": "+91 8363122463",
      "email": "sara.banerjee@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "sarafoodiehub",
      "facebook": "",
      "whatsapp": "+91 8363122463",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2021",
      "servicesOffered": "Catering, Meal Subscriptions, Workshops",
      "coverageAreas": "Indore",
      "specialties": "Catering, Continental, South Indian",
      "happyCustomers": "75+",
      "dishesServed": "200+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/sarafoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 58,
      "name": "Ishaan Joshi",
      "brandName": "Ishaan's Kitchen Studio",
      "billingName": "Ishaan Joshi Creations",
      "code": "O2C-MA786",
      "city": "Indore",
      "state": "Madhya Pradesh",
      "phone": "+91 7400563845",
      "email": "ishaan.joshi@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "ishaancooks",
      "facebook": "",
      "whatsapp": "+91 7400563845",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Catering, Home Delivery, Workshops",
      "coverageAreas": "Indore",
      "specialties": "Desserts, South Indian, Bengali, Gujarati",
      "happyCustomers": "75+",
      "dishesServed": "75+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/ishaancooks",
      "photoUrl": ""
    },
    {
      "srNo": 59,
      "name": "Rahul Iyer",
      "brandName": "Rahul's Kitchen Diaries",
      "billingName": "Rahul Iyer Media",
      "code": "O2C-MA926",
      "city": "Indore",
      "state": "Madhya Pradesh",
      "phone": "+91 8406183526",
      "email": "rahul.iyer@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "rahuleats",
      "facebook": "",
      "whatsapp": "+91 8406183526",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Catering, Meal Subscriptions",
      "coverageAreas": "Indore and nearby areas",
      "specialties": "Biryani, Street Food, Catering",
      "happyCustomers": "100+",
      "dishesServed": "150+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/rahuleats",
      "photoUrl": ""
    },
    {
      "srNo": 60,
      "name": "Kabir Sharma",
      "brandName": "Kabir's Culinary Co.",
      "billingName": "Kabir Sharma Media",
      "code": "O2C-KE485",
      "city": "Kochi",
      "state": "Kerala",
      "phone": "+91 8375769460",
      "email": "kabir.sharma@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "kabirfoodiehub",
      "facebook": "",
      "whatsapp": "+91 8375769460",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2020",
      "servicesOffered": "Catering, Workshops",
      "coverageAreas": "Kochi",
      "specialties": "Bengali, Tiffin Service, South Indian, North Indian",
      "happyCustomers": "300+",
      "dishesServed": "200+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/kabirfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 61,
      "name": "Aman Shah",
      "brandName": "Aman's Foodie Hub",
      "billingName": "Aman Shah Enterprises",
      "code": "O2C-KE453",
      "city": "Thiruvananthapuram",
      "state": "Kerala",
      "phone": "+91 8408724534",
      "email": "aman.shah@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "amaneats",
      "facebook": "",
      "whatsapp": "+91 8408724534",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Catering, Home Delivery, Meal Subscriptions",
      "coverageAreas": "Thiruvananthapuram",
      "specialties": "Bakery, Bengali, North Indian",
      "happyCustomers": "100+",
      "dishesServed": "75+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/amaneats",
      "photoUrl": ""
    },
    {
      "srNo": 62,
      "name": "Krishna Sharma",
      "brandName": "Krishna's Flavour Lab",
      "billingName": "Krishna Sharma",
      "code": "O2C-KE279",
      "city": "Thiruvananthapuram",
      "state": "Kerala",
      "phone": "+91 7423359834",
      "email": "krishna.sharma@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "krishnafoodiehub",
      "facebook": "",
      "whatsapp": "+91 7423359834",
      "kitchenType": "Café",
      "operationalSince": "2022",
      "servicesOffered": "Meal Subscriptions, Workshops",
      "coverageAreas": "Thiruvananthapuram",
      "specialties": "South Indian, Bakery, North Indian, Catering",
      "happyCustomers": "250+",
      "dishesServed": "150+",
      "rating": 4.6,
      "profileUrl": "https://instagram.com/krishnafoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 63,
      "name": "Aman Mehta",
      "brandName": "Aman's Culinary Co.",
      "billingName": "Aman Mehta",
      "code": "O2C-KE121",
      "city": "Thiruvananthapuram",
      "state": "Kerala",
      "phone": "+91 8064232527",
      "email": "aman.mehta@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "amancooks",
      "facebook": "",
      "whatsapp": "+91 8064232527",
      "kitchenType": "Café",
      "operationalSince": "2023",
      "servicesOffered": "Catering, Home Delivery, Workshops",
      "coverageAreas": "Thiruvananthapuram and nearby areas",
      "specialties": "South Indian, Thalis, Bakery, Bengali",
      "happyCustomers": "200+",
      "dishesServed": "50+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/amancooks",
      "photoUrl": ""
    },
    {
      "srNo": 64,
      "name": "Ananya Gupta",
      "brandName": "Ananya's Kitchen Tales",
      "billingName": "Ananya Gupta Enterprises",
      "code": "O2C-KE643",
      "city": "Thiruvananthapuram",
      "state": "Kerala",
      "phone": "+91 8671035415",
      "email": "ananya.gupta@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "ananyakitchen",
      "facebook": "",
      "whatsapp": "+91 8671035415",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Bulk Orders, Meal Subscriptions, Workshops",
      "coverageAreas": "Thiruvananthapuram",
      "specialties": "Biryani, Street Food, Thalis",
      "happyCustomers": "300+",
      "dishesServed": "100+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/ananyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 65,
      "name": "Tanya Kulkarni",
      "brandName": "Tanya's Spice Table",
      "billingName": "Tanya Kulkarni Creations",
      "code": "O2C-AS254",
      "city": "Guwahati",
      "state": "Assam",
      "phone": "+91 8441018950",
      "email": "tanya.kulkarni@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "tanyacooks",
      "facebook": "",
      "whatsapp": "+91 8441018950",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2018",
      "servicesOffered": "Catering, Meal Subscriptions, Workshops",
      "coverageAreas": "Guwahati",
      "specialties": "Desserts, Gujarati, South Indian",
      "happyCustomers": "200+",
      "dishesServed": "75+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/tanyacooks",
      "photoUrl": ""
    },
    {
      "srNo": 66,
      "name": "Sai Kulkarni",
      "brandName": "Sai's Chef's Table",
      "billingName": "Sai Kulkarni",
      "code": "O2C-AS573",
      "city": "Guwahati",
      "state": "Assam",
      "phone": "+91 8901682655",
      "email": "sai.kulkarni@example.com",
      "profile": "Passionate about food, flavour and community. Runs a popular kitchen known for consistent quality and a love for innovation.",
      "instagram": "saieats",
      "facebook": "",
      "whatsapp": "+91 8901682655",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Bulk Orders, Catering, Meal Subscriptions",
      "coverageAreas": "Guwahati",
      "specialties": "Gujarati, Biryani, North Indian, Continental",
      "happyCustomers": "100+",
      "dishesServed": "30+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/saieats",
      "photoUrl": ""
    },
    {
      "srNo": 67,
      "name": "Dev Das",
      "brandName": "Dev's Kitchen Tales",
      "billingName": "Dev Das Media",
      "code": "O2C-AS472",
      "city": "Guwahati",
      "state": "Assam",
      "phone": "+91 8221747079",
      "email": "dev.das@example.com",
      "profile": "Restaurant consultant and on-air cooking demo host with a decade in commercial kitchens.",
      "instagram": "deveats",
      "facebook": "",
      "whatsapp": "+91 8221747079",
      "kitchenType": "Café",
      "operationalSince": "2023",
      "servicesOffered": "Catering, Home Delivery, Meal Subscriptions",
      "coverageAreas": "Guwahati and nearby areas",
      "specialties": "South Indian, Desserts, Tiffin Service, Gujarati",
      "happyCustomers": "100+",
      "dishesServed": "75+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/deveats",
      "photoUrl": ""
    },
    {
      "srNo": 68,
      "name": "Kabir Malhotra",
      "brandName": "Kabir's Kitchen Diaries",
      "billingName": "Kabir Malhotra",
      "code": "O2C-AS232",
      "city": "Guwahati",
      "state": "Assam",
      "phone": "+91 8949821104",
      "email": "kabir.malhotra@example.com",
      "profile": "Baking specialist creating dessert-first content and running a small-batch home bakery.",
      "instagram": "kabirfoodiehub",
      "facebook": "",
      "whatsapp": "+91 8949821104",
      "kitchenType": "Café",
      "operationalSince": "2020",
      "servicesOffered": "Bulk Orders, Catering, Workshops",
      "coverageAreas": "Guwahati and nearby areas",
      "specialties": "Catering, Tiffin Service, Bakery",
      "happyCustomers": "100+",
      "dishesServed": "50+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/kabirfoodiehub",
      "photoUrl": ""
    },
    {
      "srNo": 69,
      "name": "Aadhya Patel",
      "brandName": "Aadhya's Home Chef",
      "billingName": "Aadhya Patel Media",
      "code": "O2C-BI179",
      "city": "Patna",
      "state": "Bihar",
      "phone": "+91 7969223256",
      "email": "aadhya.patel@example.com",
      "profile": "Street-food revivalist documenting local flavours and running pop-up stalls on weekends.",
      "instagram": "aadhyakitchen",
      "facebook": "",
      "whatsapp": "+91 7969223256",
      "kitchenType": "Catering Studio",
      "operationalSince": "2018",
      "servicesOffered": "Catering, Workshops",
      "coverageAreas": "Patna",
      "specialties": "Bengali, Bakery, Biryani",
      "happyCustomers": "250+",
      "dishesServed": "75+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/aadhyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 70,
      "name": "Anika Das",
      "brandName": "Anika's Chef's Table",
      "billingName": "Anika Das Creations",
      "code": "O2C-BI870",
      "city": "Patna",
      "state": "Bihar",
      "phone": "+91 9452868841",
      "email": "anika.das@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "anikacooks",
      "facebook": "",
      "whatsapp": "+91 9452868841",
      "kitchenType": "Café",
      "operationalSince": "2024",
      "servicesOffered": "Catering, Dine-in",
      "coverageAreas": "Patna and nearby areas",
      "specialties": "Desserts, Catering, Bengali",
      "happyCustomers": "250+",
      "dishesServed": "150+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/anikacooks",
      "photoUrl": ""
    },
    {
      "srNo": 71,
      "name": "Ananya Rao",
      "brandName": "Ananya's Chef's Table",
      "billingName": "Ananya Rao Media",
      "code": "O2C-BI993",
      "city": "Patna",
      "state": "Bihar",
      "phone": "+91 7819216839",
      "email": "ananya.rao@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "ananyakitchen",
      "facebook": "",
      "whatsapp": "+91 7819216839",
      "kitchenType": "Catering Studio",
      "operationalSince": "2018",
      "servicesOffered": "Home Delivery, Meal Subscriptions, Workshops",
      "coverageAreas": "Patna and nearby areas",
      "specialties": "South Indian, Biryani, Street Food, Continental",
      "happyCustomers": "125+",
      "dishesServed": "100+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/ananyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 72,
      "name": "Vivaan Banerjee",
      "brandName": "Vivaan's Kitchen Studio",
      "billingName": "Vivaan Banerjee",
      "code": "O2C-BI614",
      "city": "Patna",
      "state": "Bihar",
      "phone": "+91 8225340903",
      "email": "vivaan.banerjee@example.com",
      "profile": "Restaurant consultant and on-air cooking demo host with a decade in commercial kitchens.",
      "instagram": "vivaankitchen",
      "facebook": "",
      "whatsapp": "+91 8225340903",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2020",
      "servicesOffered": "Bulk Orders, Catering",
      "coverageAreas": "Patna and nearby areas",
      "specialties": "Desserts, South Indian, Tiffin Service",
      "happyCustomers": "300+",
      "dishesServed": "200+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/vivaankitchen",
      "photoUrl": ""
    },
    {
      "srNo": 73,
      "name": "Dev Kulkarni",
      "brandName": "Dev's Kitchen Studio",
      "billingName": "Dev Kulkarni Enterprises",
      "code": "O2C-OD119",
      "city": "Bhubaneswar",
      "state": "Odisha",
      "phone": "+91 7838638266",
      "email": "dev.kulkarni@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "devcooks",
      "facebook": "",
      "whatsapp": "+91 7838638266",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2018",
      "servicesOffered": "Bulk Orders, Catering, Home Delivery",
      "coverageAreas": "Bhubaneswar and nearby areas",
      "specialties": "South Indian, North Indian, Thalis, Bakery",
      "happyCustomers": "300+",
      "dishesServed": "150+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/devcooks",
      "photoUrl": ""
    },
    {
      "srNo": 74,
      "name": "Neha Desai",
      "brandName": "Neha's Foodie Hub",
      "billingName": "Neha Desai Media",
      "code": "O2C-OD398",
      "city": "Bhubaneswar",
      "state": "Odisha",
      "phone": "+91 8406510205",
      "email": "neha.desai@example.com",
      "profile": "Modern Indian fusion chef building a cross-platform audience and a small delivery-only kitchen.",
      "instagram": "nehaeats",
      "facebook": "",
      "whatsapp": "+91 8406510205",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2022",
      "servicesOffered": "Bulk Orders, Dine-in, Meal Subscriptions",
      "coverageAreas": "Bhubaneswar and nearby areas",
      "specialties": "Catering, Tiffin Service, South Indian",
      "happyCustomers": "50+",
      "dishesServed": "100+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/nehaeats",
      "photoUrl": ""
    },
    {
      "srNo": 75,
      "name": "Aditya Chatterjee",
      "brandName": "Aditya's Spice Table",
      "billingName": "Aditya Chatterjee Creations",
      "code": "O2C-OD865",
      "city": "Bhubaneswar",
      "state": "Odisha",
      "phone": "+91 7053256805",
      "email": "aditya.chatterjee@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "adityakitchen",
      "facebook": "",
      "whatsapp": "+91 7053256805",
      "kitchenType": "Catering Studio",
      "operationalSince": "2023",
      "servicesOffered": "Bulk Orders, Catering, Home Delivery",
      "coverageAreas": "Bhubaneswar",
      "specialties": "North Indian, Desserts, Gujarati",
      "happyCustomers": "300+",
      "dishesServed": "200+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/adityakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 76,
      "name": "Ishaan Gupta",
      "brandName": "Ishaan's Flavour Lab",
      "billingName": "Ishaan Gupta Enterprises",
      "code": "O2C-OD400",
      "city": "Bhubaneswar",
      "state": "Odisha",
      "phone": "+91 7660515741",
      "email": "ishaan.gupta@example.com",
      "profile": "Professional chef turned content creator, known for plating tutorials and quick-fire cooking reels.",
      "instagram": "ishaankitchen",
      "facebook": "",
      "whatsapp": "+91 7660515741",
      "kitchenType": "Café",
      "operationalSince": "2020",
      "servicesOffered": "Catering, Workshops",
      "coverageAreas": "Bhubaneswar and nearby areas",
      "specialties": "Gujarati, Continental, Street Food, North Indian",
      "happyCustomers": "50+",
      "dishesServed": "200+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/ishaankitchen",
      "photoUrl": ""
    },
    {
      "srNo": 77,
      "name": "Rahul Banerjee",
      "brandName": "Rahul's Cook Corner",
      "billingName": "Rahul Banerjee",
      "code": "O2C-GO495",
      "city": "Panaji",
      "state": "Goa",
      "phone": "+91 8110934486",
      "email": "rahul.banerjee@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "rahulkitchen",
      "facebook": "",
      "whatsapp": "+91 8110934486",
      "kitchenType": "Bakery",
      "operationalSince": "2020",
      "servicesOffered": "Catering, Meal Subscriptions, Workshops",
      "coverageAreas": "Panaji and nearby areas",
      "specialties": "Tiffin Service, Bakery, South Indian",
      "happyCustomers": "200+",
      "dishesServed": "30+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/rahulkitchen",
      "photoUrl": ""
    },
    {
      "srNo": 78,
      "name": "Navya Das",
      "brandName": "Navya's Chef's Table",
      "billingName": "Navya Das",
      "code": "O2C-UT270",
      "city": "Dehradun",
      "state": "Uttarakhand",
      "phone": "+91 9260268183",
      "email": "navya.das@example.com",
      "profile": "Health & nutrition-focused creator building meal-prep content for busy professionals.",
      "instagram": "navyakitchen",
      "facebook": "",
      "whatsapp": "+91 9260268183",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2019",
      "servicesOffered": "Catering, Dine-in, Home Delivery",
      "coverageAreas": "Dehradun",
      "specialties": "Catering, North Indian, South Indian, Bakery",
      "happyCustomers": "300+",
      "dishesServed": "30+",
      "rating": 4.4,
      "profileUrl": "https://instagram.com/navyakitchen",
      "photoUrl": ""
    },
    {
      "srNo": 79,
      "name": "Anika Malhotra",
      "brandName": "Anika's Spice Table",
      "billingName": "Anika Malhotra",
      "code": "O2C-UT680",
      "city": "Dehradun",
      "state": "Uttarakhand",
      "phone": "+91 7106189310",
      "email": "anika.malhotra@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "anikaeats",
      "facebook": "",
      "whatsapp": "+91 7106189310",
      "kitchenType": "Café",
      "operationalSince": "2019",
      "servicesOffered": "Catering, Dine-in, Workshops",
      "coverageAreas": "Dehradun",
      "specialties": "Bengali, Biryani, Gujarati",
      "happyCustomers": "75+",
      "dishesServed": "30+",
      "rating": 4.8,
      "profileUrl": "https://instagram.com/anikaeats",
      "photoUrl": ""
    },
    {
      "srNo": 80,
      "name": "Sneha Pillai",
      "brandName": "Sneha's Cook Corner",
      "billingName": "Sneha Pillai Enterprises",
      "code": "O2C-UT368",
      "city": "Dehradun",
      "state": "Uttarakhand",
      "phone": "+91 9539444116",
      "email": "sneha.pillai@example.com",
      "profile": "Family-style cooking creator with a strong regional following and a catering side business.",
      "instagram": "snehacooks",
      "facebook": "",
      "whatsapp": "+91 9539444116",
      "kitchenType": "Cloud Kitchen",
      "operationalSince": "2024",
      "servicesOffered": "Catering, Meal Subscriptions",
      "coverageAreas": "Dehradun and nearby areas",
      "specialties": "Thalis, South Indian, Biryani, Catering",
      "happyCustomers": "200+",
      "dishesServed": "200+",
      "rating": 4.5,
      "profileUrl": "https://instagram.com/snehacooks",
      "photoUrl": ""
    },
    {
      "srNo": 81,
      "name": "Meera Joshi",
      "brandName": "Meera's Kitchen Diaries",
      "billingName": "Meera Joshi Creations",
      "code": "O2C-JH971",
      "city": "Ranchi",
      "state": "Jharkhand",
      "phone": "+91 7516193584",
      "email": "meera.joshi@example.com",
      "profile": "Food blogger and recipe developer who turned a weekend hobby into a full-time cloud kitchen.",
      "instagram": "meeraeats",
      "facebook": "",
      "whatsapp": "+91 7516193584",
      "kitchenType": "Catering Studio",
      "operationalSince": "2024",
      "servicesOffered": "Bulk Orders, Home Delivery, Meal Subscriptions",
      "coverageAreas": "Ranchi",
      "specialties": "Biryani, Thalis, Continental",
      "happyCustomers": "100+",
      "dishesServed": "150+",
      "rating": 4.9,
      "profileUrl": "https://instagram.com/meeraeats",
      "photoUrl": ""
    },
    {
      "srNo": 82,
      "name": "Navya Chatterjee",
      "brandName": "Navya's Flavour Lab",
      "billingName": "Navya Chatterjee",
      "code": "O2C-CH887",
      "city": "Raipur",
      "state": "Chhattisgarh",
      "phone": "+91 8341685353",
      "email": "navya.chatterjee@example.com",
      "profile": "Culinary influencer specialising in regional Indian cuisine, with a growing audience of home cooks.",
      "instagram": "navyakitchen",
      "facebook": "",
      "whatsapp": "+91 8341685353",
      "kitchenType": "Home Kitchen",
      "operationalSince": "2021",
      "servicesOffered": "Catering, Home Delivery",
      "coverageAreas": "Raipur",
      "specialties": "Continental, Catering, Gujarati, Desserts",
      "happyCustomers": "50+",
      "dishesServed": "30+",
      "rating": 4.7,
      "profileUrl": "https://instagram.com/navyakitchen",
      "photoUrl": ""
    }
  ]
};
